name: Autorerun

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  rerun:
    runs-on: ubuntu-slim
    steps:
      - uses: plengauer/autorerun@v0.35.0
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
